// IndustryRoles.js — extra role families for the CoreTech Talents resume builder.
// Data only. MachiningSuggestions.jsx adds these to its own list, so the job title
// dropdown and suggestion panel work the same way for every industry.
//
// Each family: id, dept (shown in the dropdown), label, keys (what people type),
// titles, machines (tools/platforms), controls (software), skills, practices,
// bullets (work points) and summary. Keys of 3 letters or fewer only match a whole word.

const svc = (f) => ({
  instruments: [],
  practices: [],
  machinesLabel: "Tools & platforms you have used",
  controlsLabel: "Software / systems",
  practicesLabel: "Standards & practices",
  ...f,
});

export const INDUSTRY_FAMILIES = [
  // ============================ IT – SOFTWARE ============================
  svc({
    id: "swdev", dept: "IT – Software",
    label: "Software Development",
    keys: ["softwareengineer", "softwaredeveloper", "developer", "sde", "coding", "softwaredevelopment", "techlead", "associatesoftwareengineer"],
    titles: ["Software Engineer", "Software Developer", "Associate Software Engineer", "Trainee Software Engineer", "Senior Software Engineer", "Tech Lead", "Engineering Manager"],
    machines: ["Git / GitHub", "GitLab", "Bitbucket", "Jira", "Confluence", "VS Code", "IntelliJ IDEA", "Postman"],
    controls: ["Java", "Python", "JavaScript", "TypeScript", "C#", "C++", "Go", "SQL"],
    controlsLabel: "Languages",
    skills: ["Data structures & algorithms", "Object-oriented programming", "REST APIs", "Unit testing", "Code review", "Debugging", "Design patterns", "System design", "Agile / Scrum"],
    practices: ["Agile / Scrum", "Clean code", "Code reviews", "CI/CD", "Secure coding (OWASP)"],
    practicesLabel: "Methods & practices",
    bullets: [
      "Designed, developed and maintained features for a web application used by thousands of users",
      "Wrote clean, tested code and reviewed pull requests to keep quality high",
      "Fixed production bugs and improved performance of slow modules",
      "Worked in two-week Agile sprints with product, QA and design teams",
    ],
    summary: "Software Engineer experienced in building and maintaining reliable applications, with strong fundamentals in data structures, OOP, REST APIs and testing, working in Agile teams.",
  }),
  svc({
    id: "frontend", dept: "IT – Software",
    label: "Frontend / Web Development",
    keys: ["frontend", "react", "reactjs", "angular", "vue", "vuejs", "nextjs", "uideveloper", "webdeveloper", "webdesigner", "javascript", "html", "css", "wordpress"],
    titles: ["Frontend Developer", "React Developer", "Angular Developer", "UI Developer", "Web Developer", "WordPress Developer", "Senior Frontend Engineer"],
    machines: ["Git", "Figma", "Chrome DevTools", "npm / Yarn", "Vite / Webpack", "Vercel / Netlify"],
    controls: ["HTML5", "CSS3", "JavaScript (ES6+)", "TypeScript", "React", "Next.js", "Angular", "Vue.js", "Redux", "Tailwind CSS", "Bootstrap"],
    controlsLabel: "Languages & frameworks",
    skills: ["Responsive design", "Component-based UI", "State management", "REST / GraphQL integration", "Web performance", "Accessibility (WCAG)", "Cross-browser testing", "SEO basics"],
    practices: ["Mobile-first design", "Accessibility (WCAG)", "Code reviews", "Unit testing (Jest / RTL)"],
    practicesLabel: "Methods & practices",
    bullets: [
      "Built responsive, reusable UI components in React from Figma designs",
      "Integrated REST APIs and handled loading, error and empty states",
      "Improved page load speed and Lighthouse scores through code splitting and image optimisation",
      "Made pages accessible with keyboard navigation and proper labels",
    ],
    summary: "Frontend Developer skilled in React, JavaScript and modern CSS, building fast, responsive and accessible web interfaces from design to deployment.",
  }),
  svc({
    id: "backend", dept: "IT – Software",
    label: "Backend Development",
    keys: ["backend", "java", "javadeveloper", "springboot", "python", "pythondeveloper", "django", "fastapi", "flask", "dotnet", "aspnet", "nodejs", "node", "php", "laravel", "golang", "microservices"],
    titles: ["Backend Developer", "Java Developer", "Python Developer", ".NET Developer", "Node.js Developer", "PHP Developer", "Senior Backend Engineer"],
    machines: ["Git", "Docker", "Postman", "Swagger / OpenAPI", "Jenkins", "Linux"],
    controls: ["Java / Spring Boot", "Python / Django / FastAPI", "C# / .NET Core", "Node.js / Express", "PHP / Laravel", "Go", "PostgreSQL", "MySQL", "MongoDB", "Redis", "Kafka / RabbitMQ"],
    controlsLabel: "Languages, frameworks & databases",
    skills: ["REST API design", "Microservices", "Database design", "SQL query optimisation", "Authentication (JWT / OAuth)", "Caching", "Message queues", "Unit & integration testing", "Performance tuning"],
    practices: ["Clean architecture", "Code reviews", "CI/CD", "Secure coding (OWASP)"],
    practicesLabel: "Methods & practices",
    bullets: [
      "Designed and built REST APIs and microservices used by web and mobile apps",
      "Designed database schemas and optimised slow SQL queries",
      "Implemented secure login with JWT and role-based access",
      "Wrote unit and integration tests and set up CI pipelines for automatic deployment",
    ],
    summary: "Backend Developer experienced in designing REST APIs, microservices and databases, with a focus on performance, security and clean, well-tested code.",
  }),
  svc({
    id: "fullstack", dept: "IT – Software",
    label: "Full Stack Development",
    keys: ["fullstack", "mern", "mean", "fullstackdeveloper"],
    titles: ["Full Stack Developer", "MERN Stack Developer", "MEAN Stack Developer", "Senior Full Stack Engineer"],
    machines: ["Git", "Docker", "Postman", "AWS / Vercel / Railway", "Figma"],
    controls: ["React", "Angular", "Node.js / Express", "Python / Django", "MongoDB", "PostgreSQL", "MySQL", "TypeScript"],
    controlsLabel: "Languages, frameworks & databases",
    skills: ["End-to-end feature development", "REST API development", "Database design", "Authentication", "Deployment", "Responsive UI", "Debugging across the stack"],
    practices: ["Agile / Scrum", "CI/CD", "Code reviews"],
    practicesLabel: "Methods & practices",
    bullets: [
      "Built complete features end to end, from database and API to React front end",
      "Deployed applications to the cloud with automated builds",
      "Owned modules from requirement discussion to production release",
    ],
    summary: "Full Stack Developer comfortable across front end, back end and databases, delivering complete features from design to deployment.",
  }),
  svc({
    id: "mobile", dept: "IT – Software",
    label: "Mobile App Development",
    keys: ["android", "ios", "flutter", "reactnative", "mobileapp", "kotlin", "swift", "appdeveloper", "mobiledeveloper"],
    titles: ["Android Developer", "iOS Developer", "Flutter Developer", "React Native Developer", "Mobile App Developer"],
    machines: ["Android Studio", "Xcode", "Firebase", "Play Console", "App Store Connect", "Git"],
    controls: ["Kotlin", "Java", "Swift", "Dart / Flutter", "React Native", "SQLite / Room"],
    controlsLabel: "Languages & frameworks",
    skills: ["Native app development", "Cross-platform development", "REST API integration", "Push notifications", "Offline storage", "App performance tuning", "Play Store / App Store publishing"],
    practices: ["Material Design", "Human Interface Guidelines", "MVVM architecture"],
    practicesLabel: "Methods & practices",
    bullets: [
      "Developed and published Android and iOS apps with smooth, responsive screens",
      "Integrated APIs, push notifications and offline storage",
      "Reduced app crashes by fixing issues reported in Firebase Crashlytics",
    ],
    summary: "Mobile App Developer experienced in building and publishing Android and iOS apps, with strong skills in API integration, performance and user experience.",
  }),
  svc({
    id: "swtesting", dept: "IT – Software",
    label: "Software Testing / QA",
    keys: ["testing", "tester", "softwaretesting", "manualtesting", "automationtesting", "selenium", "sdet", "testengineer", "qaautomation", "istqb", "apitesting"],
    titles: ["Software Test Engineer", "QA Engineer (Software)", "Manual Tester", "Automation Test Engineer", "SDET", "Performance Test Engineer", "QA Lead"],
    machines: ["Jira", "TestRail", "Postman", "Jenkins", "BrowserStack", "Git"],
    controls: ["Selenium WebDriver", "Cypress", "Playwright", "Appium", "TestNG / JUnit", "JMeter", "Java / Python for automation", "SQL"],
    controlsLabel: "Test tools & languages",
    skills: ["Manual testing", "Test case writing", "Regression testing", "API testing", "Automation framework development", "Bug reporting", "Performance testing", "Mobile testing", "UAT support"],
    practices: ["STLC", "ISTQB practices", "Agile testing", "Defect life cycle"],
    practicesLabel: "Methods & practices",
    bullets: [
      "Wrote and executed test cases for web and mobile releases",
      "Built a Selenium automation suite that cut regression testing time significantly",
      "Tested APIs with Postman and logged clear, reproducible bugs in Jira",
      "Supported UAT and signed off releases with test reports",
    ],
    summary: "Software Test Engineer skilled in manual and automation testing with Selenium and Postman, ensuring stable, high-quality releases through thorough test coverage.",
  }),
  svc({
    id: "devops", dept: "IT – Software",
    label: "DevOps / Cloud",
    keys: ["devops", "cloud", "aws", "azure", "gcp", "kubernetes", "docker", "sre", "cicd", "terraform", "cloudengineer"],
    titles: ["DevOps Engineer", "Cloud Engineer", "AWS Engineer", "Azure Administrator", "Site Reliability Engineer (SRE)", "Platform Engineer"],
    machines: ["AWS", "Microsoft Azure", "Google Cloud", "Jenkins", "GitHub Actions", "GitLab CI"],
    controls: ["Docker", "Kubernetes", "Terraform", "Ansible", "Linux / Bash", "Prometheus / Grafana", "ELK stack", "Python scripting"],
    controlsLabel: "Tools & scripting",
    skills: ["CI/CD pipelines", "Infrastructure as code", "Containerisation", "Cloud cost optimisation", "Monitoring & alerting", "Incident response", "Linux administration", "Backup & disaster recovery"],
    practices: ["DevOps culture", "SRE practices", "Cloud security best practices"],
    practicesLabel: "Methods & practices",
    bullets: [
      "Built CI/CD pipelines that made deployments faster and repeatable",
      "Managed cloud infrastructure with Terraform and Kubernetes",
      "Set up monitoring and alerts that reduced downtime",
      "Reduced monthly cloud cost by right-sizing resources",
    ],
    summary: "DevOps Engineer experienced in CI/CD, cloud infrastructure, containers and monitoring, helping teams release faster with reliable, cost-efficient systems.",
  }),
  svc({
    id: "dataanalyst", dept: "IT – Data",
    label: "Data Analytics / BI",
    keys: ["dataanalyst", "dataanalytics", "analytics", "powerbi", "tableau", "bi", "sql", "businessintelligence", "reportinganalyst", "excelanalyst"],
    titles: ["Data Analyst", "Business Intelligence (BI) Analyst", "Power BI Developer", "Reporting Analyst", "MIS Analyst", "Senior Data Analyst"],
    machines: ["Advanced Excel", "Power BI", "Tableau", "Looker Studio", "Google Analytics"],
    controls: ["SQL", "Python (Pandas)", "R", "DAX", "Power Query"],
    controlsLabel: "Languages & tools",
    skills: ["Data cleaning", "Dashboard building", "SQL querying", "KPI reporting", "Excel (pivot tables, VLOOKUP / XLOOKUP)", "Data visualisation", "Ad-hoc analysis", "Business insights presentation"],
    bullets: [
      "Built Power BI dashboards that gave management daily visibility of key KPIs",
      "Wrote SQL queries to extract and clean data from multiple sources",
      "Automated manual Excel reports, saving hours every week",
      "Presented insights that helped teams make data-driven decisions",
    ],
    summary: "Data Analyst skilled in SQL, Excel and Power BI, turning raw data into clear dashboards and insights that support business decisions.",
  }),
  svc({
    id: "datascience", dept: "IT – Data",
    label: "Data Science / AI / Data Engineering",
    keys: ["datascience", "datascientist", "dataengineer", "machinelearning", "ml", "ai", "artificialintelligence", "deeplearning", "nlp", "genai", "llm", "mlops", "computervision", "bigdata", "spark"],
    titles: ["Data Scientist", "Machine Learning Engineer", "AI Engineer", "Data Engineer", "NLP Engineer", "Computer Vision Engineer", "MLOps Engineer"],
    machines: ["Jupyter", "AWS SageMaker", "Azure ML", "Databricks", "Snowflake", "Airflow"],
    controls: ["Python", "SQL", "scikit-learn", "TensorFlow", "PyTorch", "Pandas / NumPy", "Spark", "Hugging Face"],
    controlsLabel: "Languages & libraries",
    skills: ["Machine learning modelling", "Feature engineering", "Model evaluation", "Deep learning", "NLP", "Generative AI / LLM applications", "Data pipelines (ETL)", "Model deployment", "Statistics"],
    bullets: [
      "Built machine learning models that improved forecast accuracy for the business",
      "Designed ETL pipelines to move and clean large datasets reliably",
      "Deployed models as APIs and monitored their performance in production",
      "Built generative AI features using large language models",
    ],
    summary: "Data Scientist experienced in machine learning, data pipelines and model deployment, using Python and modern ML libraries to solve real business problems.",
  }),
  svc({
    id: "itsupport", dept: "IT – Infrastructure",
    label: "IT Support / System & Network Administration",
    keys: ["it", "itsupport", "helpdesk", "desktopsupport", "servicedesk", "systemadmin", "systemadministrator", "sysadmin", "network", "networking", "networkengineer", "ccna", "itadmin", "hardware", "hardwareengineer", "l1support", "l2support"],
    titles: ["IT Support Engineer", "Desktop Support Engineer", "Service Desk Analyst", "System Administrator", "Network Engineer", "IT Administrator", "IT Manager"],
    machines: ["Windows Server", "Active Directory", "Microsoft 365", "Google Workspace", "Cisco routers & switches", "Firewalls (Fortinet / Sophos)", "ServiceNow / Freshservice"],
    controls: ["Windows / Linux", "VMware", "Group Policy", "DHCP / DNS", "Backup tools", "Antivirus / EDR"],
    skills: ["Hardware & OS troubleshooting", "User account management", "Network setup (LAN / WAN / Wi-Fi)", "Email & Microsoft 365 administration", "Ticket handling", "Backup & restore", "Asset management", "Printer & peripheral support", "VPN setup"],
    practices: ["ITIL", "SLA-based support", "IT asset management"],
    bullets: [
      "Resolved hardware, software and network issues for users within SLA",
      "Managed Active Directory users, Microsoft 365 licences and email",
      "Set up and maintained LAN, Wi-Fi, firewall and VPN for offices and plants",
      "Maintained IT asset records and ran scheduled backups",
    ],
    summary: "IT Support Engineer experienced in desktop, server and network support, Microsoft 365 administration and ticket-based service, keeping users productive and systems secure.",
  }),
  svc({
    id: "cyber", dept: "IT – Infrastructure",
    label: "Cyber Security",
    keys: ["cybersecurity", "cyber", "infosec", "informationsecurity", "soc", "vapt", "pentest", "penetrationtesting", "ethicalhacking", "ethicalhacker", "siem", "securityanalyst"],
    titles: ["Security Analyst", "SOC Analyst", "Cyber Security Engineer", "VAPT Engineer", "Penetration Tester", "Information Security Officer"],
    machines: ["Splunk", "Microsoft Sentinel", "QRadar", "Burp Suite", "Nessus", "Wireshark", "Kali Linux"],
    controls: ["SIEM", "EDR", "Firewalls", "IDS / IPS", "Python scripting"],
    skills: ["Security monitoring", "Incident response", "Vulnerability assessment", "Penetration testing", "Threat analysis", "Security audits", "Access management", "Phishing analysis"],
    practices: ["ISO 27001", "NIST", "OWASP Top 10", "SOC 2", "DPDP Act basics"],
    bullets: [
      "Monitored security alerts in SIEM and responded to incidents quickly",
      "Performed vulnerability assessments and penetration tests on web applications",
      "Supported ISO 27001 audits with policies and evidence",
    ],
    summary: "Cyber Security Analyst experienced in SOC monitoring, incident response and VAPT, helping protect systems and data in line with ISO 27001 and OWASP practices.",
  }),
  svc({
    id: "erpconsult", dept: "IT – Enterprise Apps",
    label: "SAP / ERP / CRM Consulting",
    keys: ["sap", "sapconsultant", "erp", "oracleerp", "salesforce", "salesforcedeveloper", "crmconsultant", "functionalconsultant", "technicalconsultant", "abap", "s4hana", "dynamics", "zoho"],
    titles: ["SAP MM Consultant", "SAP SD Consultant", "SAP FICO Consultant", "SAP PP / QM Consultant", "SAP ABAP Developer", "Salesforce Developer", "ERP Consultant"],
    machines: ["SAP S/4HANA", "SAP ECC", "Oracle ERP / NetSuite", "Microsoft Dynamics 365", "Salesforce", "Zoho"],
    controls: ["ABAP", "Fiori", "Apex", "SQL"],
    skills: ["Requirement gathering", "Configuration", "Blueprint & gap analysis", "Data migration", "Integration", "User training", "UAT support", "Post go-live support"],
    practices: ["SAP Activate", "Change management", "Documentation (BBP, FS, TS)"],
    bullets: [
      "Configured SAP modules to match client business processes",
      "Led data migration and testing for an ERP go-live",
      "Trained end users and supported them after go-live",
    ],
    summary: "ERP Consultant experienced in SAP / ERP implementations and support, from requirement gathering and configuration to go-live and user training.",
  }),
  svc({
    id: "uiux", dept: "IT – Design",
    label: "UI / UX Design",
    keys: ["uiux", "ui", "ux", "uxdesigner", "uidesigner", "productdesigner", "figma", "interactiondesign", "userresearch"],
    titles: ["UI/UX Designer", "Product Designer", "UX Designer", "UI Designer", "UX Researcher"],
    machines: ["Figma", "Adobe XD", "Sketch", "Miro", "Maze", "Zeplin"],
    controls: ["Figma prototyping", "Design systems", "HTML / CSS basics"],
    controlsLabel: "Software",
    skills: ["Wireframing", "Prototyping", "User research", "Usability testing", "Design systems", "Information architecture", "Visual design", "Accessibility"],
    practices: ["Design thinking", "Human-centred design", "WCAG accessibility"],
    bullets: [
      "Designed wireframes, prototypes and final UI for web and mobile apps",
      "Ran user interviews and usability tests to improve key flows",
      "Built and maintained a design system used across products",
    ],
    summary: "UI/UX Designer who designs simple, user-friendly digital products through research, wireframes, prototypes and polished visual design in Figma.",
  }),
  svc({
    id: "itpm", dept: "IT – Management",
    label: "Business Analysis / Project & Product Management (IT)",
    keys: ["businessanalyst", "ba", "scrum", "scrummaster", "agile", "productmanager", "productowner", "itprojectmanager", "pmo", "deliverymanager", "programmanager", "techproject"],
    titles: ["Business Analyst", "Scrum Master", "Product Manager", "Product Owner", "IT Project Manager", "Delivery Manager", "Program Manager"],
    machines: ["Jira", "Confluence", "MS Project", "Azure DevOps", "Miro", "Trello"],
    controls: ["Excel", "SQL basics", "Power BI", "Visio / Lucidchart"],
    skills: ["Requirement gathering", "User stories", "BRD / FRD writing", "Sprint planning", "Stakeholder management", "Roadmap planning", "Risk management", "Status reporting", "UAT coordination"],
    practices: ["Agile / Scrum", "Kanban", "PMP / PRINCE2 practices", "SAFe"],
    bullets: [
      "Gathered requirements from stakeholders and converted them into clear user stories",
      "Ran sprint planning, stand-ups and retrospectives for a cross-functional team",
      "Delivered projects on time by tracking risks, dependencies and scope",
    ],
    summary: "IT Project and Product professional experienced in requirement analysis, Agile delivery and stakeholder management, delivering software projects on time and to scope.",
  }),
  svc({
    id: "bpo", dept: "ITES / BPO",
    label: "Customer Support / BPO / KPO",
    keys: ["bpo", "kpo", "callcenter", "callcentre", "voiceprocess", "nonvoice", "telecaller", "telecalling", "customercare", "processassociate", "chatsupport", "emailsupport", "technicalsupport", "customersupportexecutive"],
    titles: ["Customer Support Executive", "Customer Care Executive (Voice)", "Non-Voice Process Associate", "Telecaller", "Technical Support Executive", "Team Leader (BPO)", "Quality Analyst (BPO)"],
    machines: ["Zendesk", "Freshdesk", "Salesforce Service Cloud", "Dialer systems", "CRM"],
    controls: ["MS Office", "Typing (30+ WPM)", "Chat & email tools"],
    skills: ["Inbound calls", "Outbound calls", "Chat & email support", "Complaint resolution", "Upselling", "CRM data entry", "Call quality (AHT, CSAT)", "English communication", "Regional language support"],
    practices: ["SLA & TAT adherence", "Call quality guidelines", "Data privacy"],
    bullets: [
      "Handled inbound customer calls and resolved queries on first contact",
      "Maintained high CSAT scores while meeting AHT targets",
      "Updated customer records accurately in the CRM",
      "Supported customers in English, Tamil and Hindi",
    ],
    summary: "Customer Support Executive with strong communication skills, experienced in voice and non-voice support, complaint resolution and meeting CSAT and AHT targets.",
  }),

  // ============================ PHARMA ============================
  svc({
    id: "pharmaprod", dept: "Pharma",
    label: "Pharma Production (Formulation)",
    keys: ["pharmaproduction", "tablet", "tablets", "compression", "granulation", "capsule", "capsules", "coating", "blister", "blisterpacking", "osd", "oralsolid", "injectable", "injectables", "sterile", "aseptic", "parenteral", "liquidoral", "ointment", "formulationplant"],
    titles: ["Production Officer (Pharma)", "Production Chemist", "Production Executive (Pharma)", "Machine Operator – Tablet Compression", "Granulation Operator", "Capsule Filling Operator", "Packing Operator (Pharma)", "Production Manager (Pharma)"],
    machines: ["Rapid mixer granulator (RMG)", "Fluid bed dryer (FBD)", "Tablet compression machine", "Auto coater", "Capsule filling machine", "Blister packing machine", "Vial filling & sealing", "Autoclave", "Lyophiliser"],
    machinesLabel: "Machines & equipment",
    controls: ["SAP PP", "eBMR", "SCADA / HMI"],
    skills: ["Batch manufacturing (BMR / BPR)", "Dispensing", "Granulation", "Compression", "Coating", "Capsule filling", "Primary & secondary packing", "Line clearance", "In-process checks", "Cleaning & sanitisation", "Aseptic behaviour"],
    practices: ["cGMP", "GDP (Good Documentation Practices)", "Schedule M", "USFDA / MHRA / WHO-GMP", "Data integrity (ALCOA+)"],
    practicesLabel: "Regulations & practices",
    bullets: [
      "Manufactured tablet and capsule batches as per BMR under cGMP",
      "Performed line clearance, in-process checks and online documentation",
      "Operated RMG, FBD and compression machines and recorded parameters",
      "Faced USFDA and WHO-GMP audits with zero critical observations in the area",
    ],
    summary: "Pharma Production professional experienced in oral solid dosage manufacturing, BMR execution, line clearance and cGMP documentation in regulated (USFDA / WHO-GMP) plants.",
  }),
  svc({
    id: "pharmaapi", dept: "Pharma",
    label: "API / Bulk Drug Production",
    keys: ["api", "bulkdrug", "bulkdrugs", "apiplant", "reactor", "kilolab", "apiproduction"],
    titles: ["Production Chemist (API)", "Shift Chemist (API)", "Plant Operator (API)", "Production Executive (Bulk Drug)", "Kilo Lab Chemist"],
    machines: ["Reactors (SS / GLR)", "Centrifuge", "ANFD", "Tray / vacuum dryer", "Multi-mill / sifter", "Distillation units"],
    machinesLabel: "Equipment",
    controls: ["DCS / SCADA", "SAP PP", "eBMR"],
    skills: ["Reaction monitoring", "Charging & unloading", "Crystallisation", "Filtration & drying", "Solvent recovery", "Batch record documentation", "Process safety", "Yield improvement"],
    practices: ["cGMP", "ICH Q7", "Process safety management", "Data integrity"],
    practicesLabel: "Regulations & practices",
    bullets: [
      "Ran API batches in reactors as per BPR with correct temperature and time control",
      "Handled centrifuge, ANFD and dryers to deliver batches on schedule",
      "Improved batch yield through close monitoring and solvent recovery",
    ],
    summary: "API Production Chemist experienced in running bulk drug batches, reactor operations, filtration, drying and cGMP documentation with a strong focus on safety.",
  }),
  svc({
    id: "pharmaqc", dept: "Pharma",
    label: "Pharma Quality Control / Microbiology",
    keys: ["qcchemist", "qcanalyst", "hplc", "gc", "analyticalchemist", "microbiologist", "microbiology", "stability", "wetchemistry", "instrumentation", "pharmaqc"],
    titles: ["QC Chemist", "QC Analyst", "QC Executive (Pharma)", "HPLC Analyst", "Microbiologist", "Stability Analyst", "QC Manager"],
    machines: ["HPLC", "GC", "UV-Vis spectrophotometer", "FTIR", "Dissolution apparatus", "Karl Fischer titrator", "Autoclave", "Laminar air flow (LAF)"],
    machinesLabel: "Instruments",
    controls: ["Empower", "Chromeleon", "LIMS", "OpenLab"],
    skills: ["Raw material testing", "Finished product testing", "Stability testing", "Dissolution", "Method validation", "Wet chemistry", "Microbial limit test", "Environmental monitoring", "Water analysis", "OOS / OOT investigation"],
    practices: ["GLP", "cGMP", "Pharmacopoeia (IP / BP / USP)", "Data integrity (ALCOA+)", "ICH guidelines"],
    practicesLabel: "Regulations & practices",
    bullets: [
      "Analysed raw materials, in-process and finished products on HPLC and GC as per pharmacopoeia",
      "Performed stability studies and reported results on time",
      "Carried out microbial testing, water analysis and environmental monitoring",
      "Supported OOS investigations and followed data integrity practices",
    ],
    summary: "QC Chemist experienced in HPLC, GC, dissolution and wet chemistry for pharma products, following GLP, pharmacopoeia and data integrity requirements.",
  }),
  svc({
    id: "pharmaqa", dept: "Pharma",
    label: "Pharma Quality Assurance / Validation",
    keys: ["ipqa", "pharmaqa", "gmp", "cgmp", "gxp", "validation", "qualification", "capa", "changecontrol", "deviation", "csv", "qms", "qaofficer", "qualityassurancepharma"],
    titles: ["QA Officer", "IPQA Officer", "QA Executive (Pharma)", "Validation Executive", "QMS Executive", "CSV Specialist", "QA Manager (Pharma)"],
    machines: ["TrackWise", "MasterControl", "Veeva Vault", "LIMS"],
    controls: ["eQMS", "SAP QM", "Excel"],
    skills: ["IPQA line checks", "BMR / BPR review", "Batch release", "Deviation handling", "CAPA", "Change control", "Process validation", "Cleaning validation", "Equipment qualification (IQ / OQ / PQ)", "Audit handling", "SOP writing", "Annual product review (APR)"],
    practices: ["cGMP", "ICH Q8 / Q9 / Q10", "21 CFR Part 11", "EU GMP Annex 1 / 11", "Data integrity (ALCOA+)"],
    practicesLabel: "Regulations & practices",
    bullets: [
      "Performed IPQA checks, line clearance and BMR review before batch release",
      "Handled deviations, CAPA and change controls in the QMS",
      "Prepared and executed process, cleaning and equipment validation protocols",
      "Supported USFDA, MHRA and WHO audits and closed observations on time",
    ],
    summary: "Pharma QA professional experienced in IPQA, QMS (deviations, CAPA, change control), validation and regulatory audits in cGMP manufacturing sites.",
  }),
  svc({
    id: "regulatory", dept: "Pharma",
    label: "Regulatory Affairs",
    keys: ["regulatory", "regulatoryaffairs", "dossier", "ctd", "ectd", "cdsco", "usfda", "dmf", "anda", "labeling"],
    titles: ["Regulatory Affairs Executive", "Regulatory Affairs Associate", "Regulatory Affairs Manager", "Dossier Specialist", "Labelling Specialist"],
    machines: ["eCTD publishing tools", "Veeva RIM", "SUGAM portal (CDSCO)", "FDA ESG"],
    controls: ["MS Word / Adobe Acrobat", "eCTD software"],
    skills: ["Dossier compilation (CTD / eCTD)", "ANDA / DMF filing", "Query response", "Product registration", "Labelling review", "Variation filing", "Regulatory intelligence"],
    practices: ["ICH guidelines", "USFDA / EMA / CDSCO regulations", "ROW market requirements"],
    practicesLabel: "Regulations",
    bullets: [
      "Compiled and submitted CTD / eCTD dossiers for US, EU and ROW markets",
      "Responded to regulatory queries within agreed timelines",
      "Reviewed labels and artwork for regulatory compliance",
    ],
    summary: "Regulatory Affairs professional experienced in CTD / eCTD dossier preparation, submissions and query responses for regulated and ROW markets.",
  }),
  svc({
    id: "pharmarnd", dept: "Pharma",
    label: "Pharma R&D (Formulation / Analytical)",
    keys: ["formulationdevelopment", "formulationscientist", "ard", "frd", "researchscientist", "researchassociate", "pharmarnd", "rnd", "techtransfer"],
    titles: ["Research Associate (Formulation)", "Research Scientist", "Formulation Scientist", "Analytical R&D Scientist", "Tech Transfer Executive"],
    machines: ["HPLC", "Dissolution apparatus", "Lab granulator & compression", "Stability chambers"],
    machinesLabel: "Instruments & equipment",
    controls: ["Empower", "ELN", "Design Expert (DoE)"],
    skills: ["Formulation development", "Pre-formulation studies", "Analytical method development", "Method validation", "Scale-up", "Technology transfer", "QbD / DoE", "Literature search"],
    practices: ["QbD", "ICH Q8", "GLP", "Data integrity"],
    practicesLabel: "Methods & practices",
    bullets: [
      "Developed generic formulations from lab scale to exhibit batches",
      "Developed and validated analytical methods on HPLC",
      "Transferred technology to the manufacturing site and supported scale-up",
    ],
    summary: "Pharma R&D scientist experienced in formulation and analytical development, QbD, method validation and technology transfer to commercial manufacturing.",
  }),
  svc({
    id: "clinical", dept: "Pharma / Life Sciences",
    label: "Clinical Research / Pharmacovigilance",
    keys: ["clinicalresearch", "cra", "crc", "pharmacovigilance", "pv", "drugsafety", "clinicaldata", "cdm", "medicalwriting", "medicalwriter", "clinicaltrial", "clinicaltrials"],
    titles: ["Clinical Research Coordinator (CRC)", "Clinical Research Associate (CRA)", "Drug Safety Associate", "Pharmacovigilance Associate", "Clinical Data Manager", "Medical Writer"],
    machines: ["Argus Safety", "ARISg", "Medidata Rave", "Oracle Clinical", "MedDRA"],
    controls: ["EDC systems", "Safety databases", "MS Office"],
    skills: ["Case processing (ICSR)", "Adverse event reporting", "MedDRA coding", "Site monitoring", "Informed consent process", "Data cleaning & queries", "Medical writing", "Literature screening"],
    practices: ["ICH-GCP", "GVP modules", "New Drugs & Clinical Trials Rules 2019", "21 CFR Part 11"],
    practicesLabel: "Regulations",
    bullets: [
      "Processed adverse event cases and coded them in MedDRA within timelines",
      "Coordinated clinical trial activities at site as per ICH-GCP",
      "Cleaned clinical data and raised queries in the EDC system",
    ],
    summary: "Clinical Research and Pharmacovigilance professional experienced in ICSR processing, MedDRA coding, trial coordination and ICH-GCP compliance.",
  }),
  svc({
    id: "medrep", dept: "Pharma Sales",
    label: "Medical Representative / Pharma Sales",
    keys: ["mr", "medicalrepresentative", "medicalrep", "pso", "pharmasales", "abm", "areabusinessmanager", "productspecialist", "medicalsales"],
    titles: ["Medical Representative", "Professional Service Officer (PSO)", "Sr. Medical Representative", "Area Business Manager (ABM)", "Regional Sales Manager (Pharma)", "Product Specialist"],
    machines: ["SFA / CRM app", "Doctor call reporting app"],
    controls: ["Excel", "SFA app"],
    skills: ["Doctor detailing", "Chemist & stockist coverage", "Territory planning", "Prescription generation", "Product knowledge", "Sales target achievement", "Brand promotion", "CME / camp organisation"],
    practices: ["UCPMP code", "Daily call reporting"],
    practicesLabel: "Practices",
    bullets: [
      "Detailed products to doctors and grew prescriptions in the assigned territory",
      "Covered chemists and stockists to ensure product availability",
      "Achieved monthly sales targets and launched new brands successfully",
    ],
    summary: "Medical Representative with strong doctor relationships, territory planning and product detailing skills, consistently achieving sales targets.",
  }),
  svc({
    id: "pharmacist", dept: "Pharma / Healthcare",
    label: "Pharmacist",
    keys: ["pharmacist", "retailpharmacy", "hospitalpharmacy", "dispensing", "chemistshop", "medicalshop", "druginspector"],
    titles: ["Pharmacist", "Retail Pharmacist", "Hospital Pharmacist", "Clinical Pharmacist", "Pharmacy Store Manager"],
    machines: ["Pharmacy billing software", "Marg ERP", "Hospital HIS"],
    controls: ["Marg / Gofrugal", "Excel"],
    skills: ["Prescription dispensing", "Drug information", "Inventory & expiry management", "Billing", "Patient counselling", "Narcotic register maintenance", "Cold chain management"],
    practices: ["Drugs & Cosmetics Act", "Schedule H / H1 compliance", "Good pharmacy practice"],
    practicesLabel: "Regulations & practices",
    bullets: [
      "Dispensed prescriptions accurately and counselled patients on dosage",
      "Managed stock, expiry and cold chain for medicines",
      "Maintained Schedule H1 and narcotic registers as per law",
    ],
    summary: "Registered Pharmacist experienced in dispensing, patient counselling, inventory control and regulatory compliance in retail and hospital pharmacies.",
  }),

  // ============================ FACILITY MANAGEMENT ============================
  svc({
    id: "fmsoft", dept: "Facility Management",
    label: "Facility Management / Housekeeping",
    keys: ["facility", "facilities", "facilitymanagement", "facilitymanager", "fm", "ifm", "softservices", "housekeeping", "housekeepingsupervisor", "pantry", "janitorial", "cleaning"],
    titles: ["Facility Executive", "Facility Manager", "Soft Services Manager", "Housekeeping Supervisor", "Housekeeping Associate", "Pantry Associate", "FM Help Desk Executive", "Site In-charge (FM)"],
    machines: ["Scrubber drier", "Single-disc machine", "Vacuum cleaner", "High-pressure jet", "CAFM / helpdesk app"],
    machinesLabel: "Equipment & tools",
    controls: ["Excel", "CAFM software", "Attendance app"],
    skills: ["Housekeeping operations", "Manpower deployment & rostering", "Vendor management", "Pantry & cafeteria management", "Pest control coordination", "Waste management", "Client coordination", "SLA reporting", "Inventory of consumables"],
    practices: ["SLA / KPI management", "5S", "Safety & PPE", "Contract labour compliance"],
    bullets: [
      "Managed housekeeping and pantry teams across a corporate campus",
      "Prepared shift rosters and ensured full manpower deployment",
      "Met client SLAs through daily inspections and quick complaint closure",
      "Controlled consumable inventory and reduced monthly cost",
    ],
    summary: "Facility Management professional experienced in housekeeping, pantry, vendor and manpower management, delivering clean, well-run workplaces within client SLAs.",
  }),
  svc({
    id: "fmtech", dept: "Facility Management",
    label: "Technical Services / MEP",
    keys: ["mep", "hvac", "hvactechnician", "bms", "stp", "wtp", "etp", "chiller", "dgoperator", "hardservices", "plumber", "plumbing", "lift", "elevator", "firetechnician", "chiefengineer", "shiftengineer"],
    titles: ["MEP Technician", "HVAC Technician", "BMS Operator", "STP / WTP Operator", "DG Operator", "Plumber", "Shift Engineer (FM)", "Chief Engineer (FM)"],
    machines: ["Chillers & AHUs", "DG sets", "HT / LT panels", "UPS", "STP / WTP / ETP", "Fire pumps & hydrants", "Lifts", "BMS"],
    machinesLabel: "Equipment you have handled",
    controls: ["BMS software", "CAFM / PPM software"],
    skills: ["Preventive maintenance (PPM)", "Breakdown maintenance", "HVAC operation", "Electrical panel operation", "DG operation & log keeping", "Water & sewage treatment", "Fire system checks", "Energy saving", "Vendor AMC coordination"],
    practices: ["Permit to work", "LOTO", "Electrical safety", "Fire safety (NBC)"],
    bullets: [
      "Operated and maintained HVAC, DG, electrical and plumbing systems in a commercial building",
      "Completed planned preventive maintenance and kept equipment logs",
      "Ran STP and WTP within discharge norms",
      "Reduced energy consumption through chiller and lighting optimisation",
    ],
    summary: "MEP Technician experienced in operating and maintaining HVAC, electrical, DG, plumbing and STP systems in commercial facilities with strong safety practices.",
  }),
  svc({
    id: "security", dept: "Facility Management",
    label: "Security Services",
    keys: ["security", "securityguard", "guard", "watchman", "securitysupervisor", "securityofficer", "gunman", "cctv", "cctvoperator", "psara", "bouncer"],
    titles: ["Security Guard", "Security Supervisor", "Security Officer", "Gunman", "CCTV Operator", "Head – Security"],
    machines: ["CCTV / VMS", "Access control system", "Walkie-talkie", "Metal detector", "Visitor management system"],
    machinesLabel: "Equipment",
    controls: [],
    skills: ["Access control", "Patrolling", "Visitor & material gate management", "CCTV monitoring", "Emergency response", "Fire fighting basics", "First aid", "Incident reporting", "Guard deployment"],
    practices: ["PSARA norms", "Fire & evacuation drills", "Gate pass procedures"],
    bullets: [
      "Controlled entry and exit of people, vehicles and materials at the main gate",
      "Monitored CCTV and responded quickly to alarms",
      "Conducted patrols and reported incidents to management",
    ],
    summary: "Security professional experienced in access control, patrolling, CCTV monitoring and emergency response, keeping premises and people safe.",
  }),
  svc({
    id: "ehs", dept: "EHS",
    label: "Health, Safety & Environment (EHS)",
    keys: ["ehs", "hse", "safetyofficer", "safetyengineer", "safetysupervisor", "fireofficer", "firesafety", "environment", "environmentalengineer", "iso45001", "iso14001"],
    titles: ["Safety Officer", "EHS Executive", "HSE Engineer", "Fire & Safety Officer", "Safety Supervisor", "EHS Manager", "Environment Engineer"],
    machines: ["Fire extinguishers & hydrants", "Gas detectors", "Noise & lux meters", "PPE"],
    machinesLabel: "Equipment",
    controls: ["Excel", "EHS software"],
    skills: ["Hazard identification (HIRA)", "Risk assessment", "Safety inspections", "Permit to work", "Incident investigation", "Safety training", "Mock drills", "Environmental monitoring", "Statutory compliance"],
    practices: ["ISO 45001", "ISO 14001", "Factories Act (safety)", "NEBOSH / ADIS practices", "Pollution control norms"],
    bullets: [
      "Conducted HIRA and daily safety inspections and closed unsafe conditions",
      "Trained employees on PPE, fire safety and emergency response",
      "Investigated incidents and implemented corrective actions",
      "Maintained ISO 45001 and ISO 14001 records and statutory returns",
    ],
    summary: "Safety Officer experienced in HIRA, inspections, training, incident investigation and ISO 45001 / 14001 compliance, building a strong safety culture.",
  }),

  // ============================ HEALTHCARE ============================
  svc({
    id: "nursing", dept: "Healthcare",
    label: "Nursing",
    keys: ["nurse", "nursing", "staffnurse", "icunurse", "otnurse", "nursingsupervisor", "homecare", "homenurse", "gnm", "anm", "ward"],
    titles: ["Staff Nurse", "ICU Nurse", "OT Nurse", "Emergency Nurse", "Nursing Supervisor", "Home Care Nurse", "Occupational Health Nurse", "Nursing Superintendent"],
    machines: ["Patient monitors", "Ventilators", "Infusion pumps", "Defibrillator", "ECG machine", "Glucometer"],
    machinesLabel: "Equipment",
    controls: ["Hospital HIS / EMR"],
    skills: ["Patient assessment", "Medication administration", "IV cannulation", "Wound care", "Vital signs monitoring", "Critical care", "Infection control", "BLS / ACLS", "Patient documentation", "Patient & family education"],
    practices: ["NABH standards", "Infection control protocols", "BLS / ACLS"],
    bullets: [
      "Provided safe, compassionate care to patients in a busy ward",
      "Administered medicines, IV fluids and monitored vital signs",
      "Followed infection control and NABH protocols",
      "Maintained accurate nursing notes and handovers",
    ],
    summary: "Registered Staff Nurse experienced in patient care, medication administration, critical care monitoring and infection control, following NABH standards.",
  }),
  svc({
    id: "alliedhealth", dept: "Healthcare",
    label: "Allied Health / Technicians",
    keys: ["labtechnician", "mlt", "dmlt", "radiographer", "xray", "ctscan", "mri", "physiotherapist", "physio", "dialysis", "ottechnician", "optometrist", "ecgtechnician", "phlebotomist", "paramedic", "emt"],
    titles: ["Lab Technician", "Radiographer / X-ray Technician", "Physiotherapist", "Dialysis Technician", "OT Technician", "Optometrist", "Phlebotomist", "Emergency Medical Technician (EMT)"],
    machines: ["Biochemistry analyser", "Haematology analyser", "X-ray / CT / MRI", "Dialysis machine", "Physiotherapy equipment", "Autoclave"],
    machinesLabel: "Equipment",
    controls: ["LIS", "PACS", "HIS"],
    skills: ["Sample collection", "Lab testing", "Imaging procedures", "Patient positioning", "Dialysis procedure", "OT setup & sterilisation", "Physiotherapy treatment", "Report preparation", "Biomedical waste handling"],
    practices: ["NABL", "NABH", "AERB radiation safety", "Biomedical waste rules"],
    bullets: [
      "Collected and processed samples and reported results accurately",
      "Performed imaging / dialysis procedures safely as per protocol",
      "Maintained equipment, sterilisation and biomedical waste records",
    ],
    summary: "Allied Health professional experienced in diagnostic and treatment procedures, patient safety and quality standards in hospital and lab settings.",
  }),
  svc({
    id: "doctor", dept: "Healthcare",
    label: "Doctors / Medical Officers",
    keys: ["doctor", "rmo", "dutydoctor", "medicalofficer", "physician", "consultantdoctor", "dentist", "surgeon", "factorymedicalofficer", "mbbs"],
    titles: ["Duty Medical Officer", "Resident Medical Officer (RMO)", "Consultant Physician", "Factory Medical Officer", "Dentist", "General Practitioner"],
    machines: ["ECG", "Defibrillator", "Ultrasound (basic)"],
    machinesLabel: "Equipment",
    controls: ["HIS / EMR"],
    skills: ["Patient examination & diagnosis", "Emergency management", "Prescription", "Occupational health checks", "Ward rounds", "Referral coordination", "Medical documentation"],
    practices: ["NMC ethics", "NABH standards", "Factories Act (medical)"],
    bullets: [
      "Examined, diagnosed and treated OPD and emergency patients",
      "Conducted pre-employment and periodic health check-ups for factory workers",
      "Maintained medical records and coordinated referrals",
    ],
    summary: "Medical Officer experienced in OPD, emergency care and occupational health, providing prompt, ethical patient care.",
  }),
  svc({
    id: "hospitaladmin", dept: "Healthcare",
    label: "Hospital Administration / Medical Coding",
    keys: ["medicalcoding", "medicalcoder", "cpc", "medicalbilling", "rcm", "hospitaladmin", "hospitaladministration", "tpa", "insurancedesk", "patientcare", "frontofficehospital", "medicalscribe", "mrd"],
    titles: ["Medical Coder", "Medical Billing Executive", "AR Caller (RCM)", "TPA / Insurance Executive", "Hospital Front Office Executive", "Patient Care Coordinator", "Hospital Administrator"],
    machines: ["HIS", "Encoder tools", "TPA portals"],
    controls: ["ICD-10-CM", "CPT", "HCPCS", "Excel"],
    controlsLabel: "Code sets & software",
    skills: ["ICD-10 / CPT coding", "Claims processing", "Denial management", "AR follow-up", "Cashless / TPA processing", "Patient registration", "Appointment scheduling", "MRD maintenance"],
    practices: ["HIPAA", "NABH", "Coding guidelines"],
    bullets: [
      "Coded medical charts accurately using ICD-10-CM and CPT",
      "Followed up insurance claims and reduced denials",
      "Handled cashless admissions and TPA approvals",
    ],
    summary: "Healthcare administration professional experienced in medical coding, billing, insurance / TPA processing and patient services.",
  }),

  // ============================ BFSI ============================
  svc({
    id: "banking", dept: "Banking & Finance",
    label: "Banking / Loans / Finance Operations",
    keys: ["bank", "banking", "relationshipmanager", "loan", "loans", "loanofficer", "credit", "creditanalyst", "creditmanager", "collections", "collection", "branchmanager", "kyc", "aml", "fintech", "nbfc", "microfinance", "financialanalyst", "fpa", "investment"],
    titles: ["Relationship Manager", "Loan Officer", "Credit Analyst", "Collection Officer", "Branch Manager", "KYC / AML Analyst", "Financial Analyst", "Personal Banker"],
    machines: ["Core banking (Finacle / Flexcube)", "CIBIL / bureau portals", "LOS / LMS"],
    controls: ["Finacle", "Excel", "Bloomberg (basic)"],
    skills: ["Customer acquisition", "Loan sourcing", "Credit appraisal", "Financial statement analysis", "Collections & recovery", "KYC verification", "AML screening", "Cross-selling", "Branch operations", "Financial modelling"],
    practices: ["RBI guidelines", "KYC / AML norms", "Fair practices code"],
    bullets: [
      "Sourced and processed loans while meeting monthly disbursement targets",
      "Appraised credit proposals by analysing financials and bureau reports",
      "Managed collections and reduced overdue accounts in the portfolio",
      "Completed KYC checks and AML screening as per RBI norms",
    ],
    summary: "Banking professional experienced in loan sourcing, credit appraisal, collections and KYC compliance, delivering targets while following RBI norms.",
  }),
  svc({
    id: "insurance", dept: "Banking & Finance",
    label: "Insurance",
    keys: ["insurance", "insuranceadvisor", "underwriter", "underwriting", "claims", "claimsexecutive", "lifeinsurance", "healthinsurance", "bancassurance", "posp"],
    titles: ["Insurance Advisor", "Sales Manager (Insurance)", "Underwriter", "Claims Executive", "Bancassurance Officer", "Policy Servicing Executive"],
    machines: ["Insurer portals", "CRM"],
    controls: ["Excel", "Policy admin systems"],
    skills: ["Policy selling", "Needs analysis", "Underwriting", "Claims processing", "Renewals", "Customer service", "Agent recruitment"],
    practices: ["IRDAI regulations", "KYC norms"],
    bullets: [
      "Sold life and health policies and consistently met premium targets",
      "Processed claims accurately within turnaround time",
      "Improved renewal rates through regular customer follow-up",
    ],
    summary: "Insurance professional experienced in policy sales, underwriting and claims, following IRDAI norms with a strong customer focus.",
  }),

  // ============================ RETAIL / E-COMMERCE / DELIVERY ============================
  svc({
    id: "retail", dept: "Retail",
    label: "Retail Store Operations",
    keys: ["retail", "cashier", "storemanager", "retailsales", "salesassociate", "showroom", "merchandiser", "visualmerchandiser", "visualmerchandising", "floorsupervisor", "categorymanager", "supermarket"],
    titles: ["Retail Sales Associate", "Cashier", "Store Manager", "Assistant Store Manager", "Floor Supervisor", "Visual Merchandiser", "Category Manager", "Showroom Sales Executive"],
    machines: ["POS billing", "Barcode scanner", "Card / UPI terminals"],
    controls: ["POS software", "Excel"],
    skills: ["Customer handling", "Billing & cash handling", "Product display", "Stock replenishment", "Upselling", "Inventory counting", "Store opening & closing", "Staff scheduling", "Sales target achievement"],
    practices: ["Visual merchandising standards", "Shrinkage control", "Customer service standards"],
    bullets: [
      "Helped customers choose products and consistently met sales targets",
      "Handled billing and cash accurately with zero shortages",
      "Maintained attractive displays and replenished stock on time",
      "Led store team and improved monthly sales and customer ratings",
    ],
    summary: "Retail professional experienced in customer service, billing, visual merchandising and store operations, driving sales and customer satisfaction.",
  }),
  svc({
    id: "delivery", dept: "Delivery & Driving",
    label: "Delivery / Driver",
    keys: ["delivery", "deliveryboy", "deliveryexecutive", "rider", "driver", "lmv", "hmv", "heavyvehicle", "cab", "chauffeur", "courier", "companydriver", "truckdriver", "busdriver"],
    titles: ["Delivery Executive", "Delivery Rider", "Company Driver", "Car Driver (LMV)", "Truck Driver (HMV)", "Bus Driver", "Courier Associate"],
    machines: ["Two-wheeler", "Car (LMV)", "Truck / bus (HMV)", "Delivery app", "Google Maps"],
    machinesLabel: "Vehicles & apps",
    controls: [],
    skills: ["Safe driving", "Route planning", "On-time delivery", "Cash on delivery handling", "Customer handling", "Vehicle upkeep", "Trip log maintenance"],
    practices: ["Valid driving licence (LMV / HMV)", "Road safety rules", "Defensive driving"],
    practicesLabel: "Licences & practices",
    bullets: [
      "Delivered orders on time within the assigned area",
      "Handled cash on delivery accurately and politely resolved customer issues",
      "Maintained a clean driving record and kept the vehicle in good condition",
    ],
    summary: "Reliable driver / delivery executive with a valid licence, good route knowledge and a clean safety record, committed to on-time delivery.",
  }),

  // ============================ HOSPITALITY ============================
  svc({
    id: "hotel", dept: "Hospitality",
    label: "Hotel / Restaurant",
    keys: ["hotel", "chef", "cook", "commis", "cdp", "sous", "steward", "waiter", "fnb", "foodandbeverage", "restaurant", "kitchen", "bakery", "baker", "barista", "bartender", "hospitality", "roomattendant", "frontofficehotel", "catering"],
    titles: ["Commis Chef", "Chef de Partie (CDP)", "Cook", "F&B Steward", "Restaurant Captain", "Front Office Associate (Hotel)", "Room Attendant", "Barista", "F&B Manager"],
    machines: ["Commercial kitchen equipment", "Combi oven", "Tandoor", "Coffee machine", "POS"],
    machinesLabel: "Equipment",
    controls: ["IDS / Opera PMS", "POS"],
    skills: ["Food preparation", "Menu planning", "Food costing", "Guest service", "Table service", "Room check-in / check-out", "Housekeeping standards", "Complaint handling", "Kitchen hygiene"],
    practices: ["FSSAI hygiene", "HACCP", "Guest service standards"],
    bullets: [
      "Prepared dishes to recipe standards during high-volume service",
      "Delivered warm, efficient guest service and handled complaints well",
      "Maintained kitchen hygiene as per FSSAI and HACCP",
    ],
    summary: "Hospitality professional experienced in food preparation and guest service, with a strong focus on hygiene, consistency and guest satisfaction.",
  }),

  // ============================ EDUCATION ============================
  svc({
    id: "teaching", dept: "Education",
    label: "Teaching / Training",
    keys: ["teacher", "teaching", "lecturer", "professor", "assistantprofessor", "tutor", "faculty", "prt", "tgt", "pgt", "corporatetrainer", "technicaltrainer", "academiccoordinator", "principal", "counsellor", "instructor", "itiinstructor"],
    titles: ["Primary Teacher (PRT)", "TGT Teacher", "PGT Teacher", "Assistant Professor", "Lecturer", "ITI Instructor", "Corporate Trainer", "Academic Coordinator"],
    machines: ["Smart board", "LMS (Moodle / Google Classroom)", "Zoom / Teams"],
    controls: ["MS Office", "Google Workspace"],
    skills: ["Lesson planning", "Classroom management", "Student assessment", "Parent communication", "Online teaching", "Curriculum development", "Training need analysis", "Mentoring"],
    practices: ["NEP 2020", "CBSE / State board curriculum", "Outcome-based education"],
    bullets: [
      "Planned and delivered engaging lessons that improved student results",
      "Assessed students regularly and supported weak learners",
      "Trained employees / students on technical and soft skills",
    ],
    summary: "Educator experienced in lesson planning, engaging teaching and student assessment, helping learners improve results and confidence.",
  }),

  // ============================ MARKETING / MEDIA ============================
  svc({
    id: "digitalmkt", dept: "Marketing",
    label: "Digital Marketing / Content",
    keys: ["digitalmarketing", "seo", "sem", "smm", "socialmedia", "socialmediamanager", "contentwriter", "content", "copywriter", "copywriting", "performancemarketing", "googleads", "metaads", "emailmarketing", "brandmanager", "marketingexecutive"],
    titles: ["Digital Marketing Executive", "SEO Specialist", "Social Media Manager", "Performance Marketing Specialist", "Content Writer", "Copywriter", "Brand Manager"],
    machines: ["Google Ads", "Meta Ads Manager", "Google Analytics 4", "Search Console", "SEMrush / Ahrefs", "Mailchimp", "Canva"],
    controls: ["WordPress", "HubSpot", "Excel"],
    skills: ["SEO (on-page / off-page)", "Paid ads (PPC)", "Social media content", "Content writing", "Email marketing", "Campaign analytics", "Lead generation", "Brand strategy", "A/B testing"],
    practices: ["Google & Meta ad policies", "Brand guidelines"],
    bullets: [
      "Grew organic traffic through keyword research and on-page SEO",
      "Ran Google and Meta ad campaigns that lowered cost per lead",
      "Created social media content that increased followers and engagement",
      "Tracked campaign results in GA4 and reported insights weekly",
    ],
    summary: "Digital Marketing professional experienced in SEO, paid ads, social media and content, driving traffic, leads and brand growth with measurable results.",
  }),
  svc({
    id: "creative", dept: "Media & Design",
    label: "Graphic Design / Video / Media",
    keys: ["graphicdesign", "graphicdesigner", "videoeditor", "videoediting", "animator", "animation", "motiongraphics", "photographer", "photography", "photoshop", "illustrator", "vfx", "journalist", "reporter", "editor"],
    titles: ["Graphic Designer", "Video Editor", "Motion Graphics Designer", "Animator (2D / 3D)", "Photographer", "Journalist / Reporter", "Content Creator"],
    machines: ["Adobe Photoshop", "Adobe Illustrator", "Adobe Premiere Pro", "After Effects", "CorelDRAW", "Canva", "Blender", "DaVinci Resolve"],
    controls: [],
    skills: ["Brand identity design", "Social media creatives", "Print design", "Video editing", "Motion graphics", "Photography & retouching", "Storyboarding", "Typography"],
    practices: ["Brand guidelines", "Print production standards"],
    bullets: [
      "Designed social media creatives, brochures and branding for multiple clients",
      "Edited videos and reels that increased views and engagement",
      "Delivered print-ready files and managed feedback rounds on time",
    ],
    summary: "Creative professional skilled in graphic design and video editing, producing on-brand visuals and videos that engage audiences.",
  }),

  // ============================ CONSTRUCTION ============================
  svc({
    id: "civil", dept: "Construction",
    label: "Civil / Construction Engineering",
    keys: ["civil", "civilengineer", "siteengineer", "construction", "quantitysurveyor", "qs", "billingengineer", "sitesupervisor", "structural", "planningengineer", "infrastructure", "interior", "interiordesigner", "architect", "interiordesign"],
    titles: ["Site Engineer (Civil)", "Civil Engineer", "Site Supervisor", "Quantity Surveyor", "Billing Engineer", "Planning Engineer (Construction)", "Project Manager (Construction)", "Interior Designer", "Architect"],
    machines: ["Total station", "Auto level", "Concrete testing equipment"],
    machinesLabel: "Instruments",
    controls: ["AutoCAD", "Revit", "STAAD Pro", "MS Project / Primavera", "SketchUp", "3ds Max"],
    skills: ["Site execution", "Quantity estimation", "BOQ preparation", "Contractor billing", "Surveying & levelling", "Quality checks (concrete, steel)", "Drawing reading", "Project scheduling", "Labour management"],
    practices: ["IS codes", "Site safety", "Quality checklists"],
    bullets: [
      "Executed building works as per drawings, specifications and schedule",
      "Prepared BOQ, quantity estimates and contractor bills",
      "Checked concrete, steel and finishing quality at site",
      "Coordinated labour, materials and subcontractors daily",
    ],
    summary: "Civil Engineer experienced in site execution, quantity estimation, billing and quality control, delivering construction projects on time and within budget.",
  }),
  svc({
    id: "trades", dept: "Construction",
    label: "Construction & Skilled Trades",
    keys: ["mason", "barbender", "carpenter", "scaffolder", "shuttering", "painter", "helper", "tiles", "tiler", "constructionworker", "labour", "steelfixer", "rigger"],
    titles: ["Mason", "Carpenter", "Bar Bender", "Shuttering Carpenter", "Painter", "Scaffolder", "Rigger", "Construction Helper"],
    machines: ["Mixer machine", "Vibrator", "Cutting machine", "Drill machine", "Scaffolding"],
    machinesLabel: "Tools & equipment",
    controls: [],
    skills: ["Brickwork & plastering", "Tiling", "Shuttering", "Bar bending & tying", "Painting & finishing", "Scaffolding", "Reading basic drawings", "Measuring & marking"],
    practices: ["Height safety", "PPE usage", "Site housekeeping"],
    bullets: [
      "Completed brickwork, plastering and tiling with neat finish",
      "Followed height safety and PPE rules at all times",
      "Worked with the team to finish tasks within schedule",
    ],
    summary: "Skilled construction tradesperson with hands-on experience and a strong focus on quality finish and site safety.",
  }),

  // ============================ OTHER MANUFACTURING & PROCESS ============================
  svc({
    id: "electronics", dept: "Electronics / Electrical",
    label: "Electronics & Electrical Engineering",
    keys: ["electronics", "smt", "pcb", "pcba", "soldering", "embedded", "firmware", "iot", "hardwaredesign", "electricalengineer", "electricaldesign", "electronicsengineer", "wireharness", "ems"],
    titles: ["Electronics Technician", "SMT Operator", "PCB Assembly Operator", "Embedded Engineer", "Electrical Design Engineer", "Test Technician (Electronics)", "Wire Harness Operator"],
    machines: ["SMT pick & place", "Reflow oven", "Wave soldering", "AOI", "Oscilloscope", "Multimeter", "Soldering station"],
    machinesLabel: "Machines & equipment",
    controls: ["Altium", "KiCad", "EPLAN", "AutoCAD Electrical", "Embedded C", "Keil / STM32 tools"],
    skills: ["PCB assembly", "Hand soldering", "SMT line operation", "Circuit testing & debugging", "Firmware development", "Schematic design", "Panel design", "Component identification", "ESD handling"],
    practices: ["IPC-A-610", "ESD control", "IEC standards"],
    bullets: [
      "Operated SMT lines and assembled PCBs to IPC-A-610 standards",
      "Tested and debugged boards using oscilloscope and multimeter",
      "Designed schematics and wrote embedded firmware for product features",
    ],
    summary: "Electronics professional experienced in PCB assembly, testing, embedded development and electrical design, following IPC and ESD standards.",
  }),
  svc({
    id: "textile", dept: "Textile & Garments",
    label: "Textile / Garments",
    keys: ["textile", "garment", "garments", "tailor", "sewing", "sewingmachine", "stitching", "patternmaker", "spinning", "weaving", "knitting", "apparel", "fabric", "dyeing", "fashiondesigner", "garmentmerchandiser"],
    titles: ["Sewing Machine Operator", "Tailor", "Pattern Maker", "Cutting Master", "Garment Quality Checker", "Garment Merchandiser", "Fashion Designer", "Spinning / Weaving Operator"],
    machines: ["Single-needle lock stitch", "Overlock machine", "Flatlock machine", "Cutting machine", "Spinning frames", "Looms", "Knitting machines"],
    machinesLabel: "Machines",
    controls: ["Gerber / Lectra CAD", "ERP"],
    skills: ["Garment stitching", "Pattern making", "Cutting & marker planning", "Quality checking", "Measurement checking", "Order follow-up", "Buyer communication", "Fabric sourcing"],
    practices: ["AQL inspection", "Buyer compliance (social audits)", "Lean in garments"],
    bullets: [
      "Stitched garments to buyer specifications while meeting hourly targets",
      "Checked garments for defects and measurements as per AQL",
      "Followed up orders with buyers and suppliers to ship on time",
    ],
    summary: "Textile and garment professional experienced in stitching, pattern making, quality checking and merchandising for export and domestic orders.",
  }),
  svc({
    id: "food", dept: "Food & FMCG",
    label: "Food Processing / FMCG",
    keys: ["food", "foodprocessing", "foodtechnologist", "fssai", "haccp", "fmcg", "dairy", "beverage", "foodsafety", "packagingoperator"],
    titles: ["Production Operator (Food)", "Food Technologist", "Quality Executive (Food)", "Food Safety Officer", "Packing Supervisor (FMCG)", "Production Supervisor (FMCG)"],
    machines: ["Mixers & blenders", "Ovens & fryers", "Form-fill-seal (FFS) machines", "Pasteuriser", "Retort", "Metal detector"],
    machinesLabel: "Machines & equipment",
    controls: ["SAP", "Excel"],
    skills: ["Food production", "Recipe & batch control", "Quality testing", "Shelf-life studies", "Packing line operation", "Hygiene & sanitation", "GMP in food", "Allergen control"],
    practices: ["FSSAI", "HACCP", "ISO 22000", "FSSC 22000", "BRCGS"],
    bullets: [
      "Ran food production lines as per recipe, hygiene and safety standards",
      "Tested raw materials and finished goods and released batches",
      "Maintained HACCP and FSSAI records for audits",
    ],
    summary: "Food and FMCG professional experienced in production, quality testing and food safety systems such as HACCP, FSSAI and FSSC 22000.",
  }),
  svc({
    id: "chemical", dept: "Chemical / Process",
    label: "Chemical / Process Plant Operations",
    keys: ["chemical", "chemicalengineer", "chemicalplant", "processplant", "dcs", "boiler", "boileroperator", "paneloperator", "refinery", "petrochemical", "plantoperator", "shiftchemist", "fieldoperator", "oilandgas", "fertilizer", "paint"],
    titles: ["Plant Operator", "DCS Panel Operator", "Boiler Operator", "Shift Chemist", "Process Engineer (Chemical)", "Field Operator", "Shift In-charge (Process)"],
    machines: ["Reactors", "Distillation columns", "Heat exchangers", "Boilers", "Pumps & compressors", "Cooling towers"],
    machinesLabel: "Equipment",
    controls: ["DCS (Honeywell / Yokogawa / ABB)", "PLC / SCADA", "SAP PM"],
    skills: ["Plant start-up & shutdown", "DCS operation", "Process parameter control", "Boiler operation", "Sampling & lab coordination", "Troubleshooting", "Log sheet maintenance", "Process safety"],
    practices: ["Process safety management (PSM)", "HAZOP", "Permit to work", "Boiler Act / IBR"],
    bullets: [
      "Operated the plant through DCS, keeping parameters within limits",
      "Carried out safe start-up and shutdown procedures",
      "Maintained log sheets and coordinated sampling with the lab",
    ],
    summary: "Process Plant Operator experienced in DCS operation, plant start-up and shutdown, boiler operation and process safety in chemical plants.",
  }),
  svc({
    id: "autoservice", dept: "Automobile Service",
    label: "Automobile Service / Workshop",
    keys: ["automobile", "autoservice", "serviceadvisor", "workshop", "twowheeler", "fourwheeler", "carmechanic", "bikemechanic", "bodyshop", "denting", "autoelectrician", "servicetechnician", "dealership"],
    titles: ["Service Advisor", "Automobile Technician", "Two-Wheeler Mechanic", "Car Mechanic", "Auto Electrician", "Body Shop Technician", "Workshop Manager"],
    machines: ["Diagnostic scanner", "Wheel alignment machine", "Hydraulic lift", "Pneumatic tools"],
    machinesLabel: "Equipment",
    controls: ["DMS (dealer management system)", "Excel"],
    skills: ["Vehicle servicing", "Engine repair", "Electrical diagnosis", "Denting & painting", "Job card creation", "Customer handling", "Estimation", "Warranty claims"],
    practices: ["OEM service standards", "Workshop safety"],
    bullets: [
      "Serviced and repaired vehicles as per OEM standards",
      "Diagnosed electrical faults using scanners",
      "Explained work to customers and prepared accurate estimates",
    ],
    summary: "Automobile service professional experienced in vehicle servicing, diagnostics and customer handling at dealership workshops.",
  }),
  svc({
    id: "telecom", dept: "Telecom",
    label: "Telecom",
    keys: ["telecom", "rf", "rfengineer", "fiber", "fibre", "ftth", "ofc", "splicer", "splicing", "tower", "towertechnician", "5g", "4g", "bts"],
    titles: ["Telecom Technician", "RF Engineer", "FTTH Technician", "Fiber Splicer", "Tower Technician", "Network Operations (NOC) Engineer"],
    machines: ["OTDR", "Fusion splicer", "Power meter", "Spectrum analyser"],
    machinesLabel: "Equipment",
    controls: ["NMS tools", "Drive test tools"],
    skills: ["Fiber laying & splicing", "FTTH installation", "BTS installation", "RF optimisation", "Drive testing", "Fault rectification", "Site surveys"],
    practices: ["Height safety", "Telecom site safety"],
    bullets: [
      "Installed and maintained FTTH connections for home and business customers",
      "Spliced and tested fiber with OTDR to fix faults quickly",
      "Optimised RF parameters to improve network coverage",
    ],
    summary: "Telecom professional experienced in fiber and FTTH installation, splicing and RF work, keeping networks reliable.",
  }),
  svc({
    id: "energy", dept: "Energy / Power",
    label: "Solar / Power / Renewable Energy",
    keys: ["solar", "solarpv", "solartechnician", "rooftop", "substation", "windturbine", "powerplant", "renewable", "transmission", "electricalsupervisor", "lineman", "ev", "evcharging"],
    titles: ["Solar Technician", "Solar Installation Engineer", "Substation Operator", "Electrical Supervisor", "Wind Turbine Technician", "Lineman", "O&M Engineer (Solar)"],
    machines: ["Solar panels & inverters", "HT / LT switchgear", "Transformers", "SCADA", "IR thermography"],
    machinesLabel: "Equipment",
    controls: ["PVsyst", "AutoCAD", "SCADA"],
    skills: ["Solar installation", "Inverter commissioning", "O&M of solar plants", "Substation operation", "Electrical testing", "Earthing & protection", "Energy yield monitoring"],
    practices: ["CEA regulations", "Electrical safety", "Working at height"],
    practicesLabel: "Regulations & practices",
    bullets: [
      "Installed and commissioned rooftop and ground-mount solar systems",
      "Maintained plant uptime through preventive maintenance and quick fault fixing",
      "Operated substation equipment safely as per switching procedures",
    ],
    summary: "Energy professional experienced in solar installation, O&M and substation operation, with strong electrical safety practices.",
  }),

  // ============================ OTHER SERVICES ============================
  svc({
    id: "legal", dept: "Legal",
    label: "Legal / Compliance",
    keys: ["legal", "lawyer", "advocate", "paralegal", "litigation", "contracts", "contractmanagement", "legalexecutive", "compliance", "complianceofficer", "companysecretary", "secretarial", "cs"],
    titles: ["Legal Executive", "Legal Associate / Advocate", "Legal Manager", "Compliance Officer", "Company Secretary", "Paralegal", "Contract Manager"],
    machines: ["SCC Online / Manupatra", "MCA portal", "e-Courts"],
    controls: ["MS Word", "Contract management tools"],
    skills: ["Contract drafting & review", "Legal research", "Litigation support", "Regulatory compliance", "Board & ROC filings", "Legal notices", "Due diligence", "IP basics"],
    practices: ["Companies Act 2013", "Indian Contract Act", "Labour laws", "SEBI regulations (listed cos)"],
    practicesLabel: "Laws",
    bullets: [
      "Drafted and reviewed contracts, NDAs and vendor agreements",
      "Managed litigation matters and coordinated with external counsel",
      "Completed ROC filings and board compliances on time",
    ],
    summary: "Legal professional experienced in contract drafting, litigation support and corporate compliance under Indian law.",
  }),
  svc({
    id: "realestate", dept: "Real Estate",
    label: "Real Estate",
    keys: ["realestate", "property", "propertyconsultant", "leasing", "channelpartner", "broker", "presales", "realestatecrm"],
    titles: ["Property Consultant", "Real Estate Sales Executive", "Pre-Sales Executive", "Leasing Manager", "CRM Executive (Real Estate)", "Channel Partner Manager"],
    machines: ["Property portals (99acres, MagicBricks)", "CRM"],
    controls: ["Excel", "CRM"],
    skills: ["Site visits", "Lead follow-up", "Negotiation", "Booking & documentation", "Channel partner management", "Customer relationship"],
    practices: ["RERA norms"],
    practicesLabel: "Regulations",
    bullets: [
      "Converted leads into bookings through site visits and follow-ups",
      "Handled booking documentation and customer queries till possession",
      "Built a strong channel partner network for new projects",
    ],
    summary: "Real estate sales professional experienced in lead conversion, site visits and customer relationships, following RERA norms.",
  }),
  svc({
    id: "wellness", dept: "Beauty & Wellness",
    label: "Beauty, Fitness & Wellness",
    keys: ["beautician", "beauty", "salon", "hairstylist", "hairdresser", "makeup", "makeupartist", "spa", "spatherapist", "gym", "fitnesstrainer", "personaltrainer", "yoga", "yogainstructor", "zumba", "dietitian", "nutritionist"],
    titles: ["Beautician", "Hair Stylist", "Makeup Artist", "Spa Therapist", "Fitness Trainer", "Yoga Instructor", "Nutritionist / Dietitian"],
    machines: ["Salon equipment", "Gym equipment", "Booking app"],
    machinesLabel: "Equipment",
    controls: [],
    skills: ["Hair cutting & styling", "Skin care & facials", "Makeup", "Spa therapies", "Workout planning", "Diet planning", "Client consultation", "Hygiene & sanitation"],
    practices: ["Hygiene standards", "Certified training (e.g. ACE / Yoga certification)"],
    bullets: [
      "Delivered high-quality services and built a loyal client base",
      "Consulted clients to recommend suitable treatments or plans",
      "Maintained hygiene and safety standards at all times",
    ],
    summary: "Beauty and wellness professional skilled in client consultation and high-quality services, with a loyal client base and strong hygiene standards.",
  }),
  svc({
    id: "aviation", dept: "Aviation",
    label: "Aviation",
    keys: ["aviation", "cabincrew", "airhostess", "flightattendant", "groundstaff", "airport", "ame", "aircraftmaintenance", "rampagent", "airlines"],
    titles: ["Cabin Crew", "Ground Staff", "Airport Customer Service Agent", "Ramp Agent", "Aircraft Maintenance Engineer (AME)", "Aircraft Technician"],
    machines: ["Aircraft ground support equipment", "Departure control systems"],
    machinesLabel: "Equipment & systems",
    controls: ["Amadeus / Navitaire", "AMOS"],
    skills: ["Passenger service", "Check-in & boarding", "Safety demonstrations", "Aircraft inspection", "Line maintenance", "Documentation (logbooks)", "Emergency procedures"],
    practices: ["DGCA regulations", "CAR-66 / CAR-145", "Aviation safety"],
    practicesLabel: "Regulations",
    bullets: [
      "Delivered courteous passenger service during check-in, boarding and flights",
      "Carried out line maintenance and inspections as per DGCA rules",
      "Followed safety and emergency procedures strictly",
    ],
    summary: "Aviation professional experienced in passenger service / aircraft maintenance, following DGCA safety regulations.",
  }),
  svc({
    id: "backoffice", dept: "General Office",
    label: "Back Office / Data Entry",
    keys: ["dataentry", "dataentryoperator", "backoffice", "computeroperator", "officeboy", "peon", "mis", "misexecutive", "typist", "documentation", "documentcontroller", "receptionistoffice"],
    titles: ["Data Entry Operator", "Back Office Executive", "Computer Operator", "MIS Executive", "Document Controller", "Office Assistant", "Office Boy"],
    machines: ["Computer", "Printer & scanner", "Photocopier"],
    machinesLabel: "Equipment",
    controls: ["MS Excel", "MS Word", "Tally", "Google Sheets", "Typing (English / Tamil)"],
    skills: ["Fast & accurate typing", "Data entry", "Excel reports", "File management", "Document scanning & filing", "Email handling", "Record keeping"],
    practices: ["Data accuracy checks", "Confidentiality"],
    bullets: [
      "Entered and verified large volumes of data with high accuracy",
      "Prepared daily MIS reports in Excel for management",
      "Maintained physical and digital files in an organised way",
    ],
    summary: "Back Office Executive with fast, accurate typing and strong Excel skills, experienced in data entry, MIS reports and record keeping.",
  }),
  svc({
    id: "ngo", dept: "Social Sector",
    label: "NGO / CSR / Social Work",
    keys: ["ngo", "socialwork", "socialworker", "csr", "fieldcoordinator", "programofficer", "communitymobiliser", "developmentsector", "livelihood"],
    titles: ["Programme Officer", "Field Coordinator", "CSR Executive", "Community Mobiliser", "Social Worker", "Project Coordinator (NGO)"],
    machines: ["KoBoToolbox", "Google Forms"],
    controls: ["Excel", "MS Office"],
    skills: ["Community mobilisation", "Programme implementation", "Monitoring & evaluation", "Report writing", "Stakeholder coordination", "Beneficiary data management", "Fundraising support"],
    practices: ["Companies Act CSR rules (Schedule VII)", "M&E frameworks"],
    practicesLabel: "Frameworks",
    bullets: [
      "Implemented community programmes and reached target beneficiaries",
      "Collected field data and prepared monitoring reports for donors",
      "Coordinated with government bodies and local partners",
    ],
    summary: "Development sector professional experienced in programme implementation, community mobilisation and monitoring for NGO and CSR projects.",
  }),
];